version: "3.3"
    
services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: dontusethispassword
      MYSQL_DATABASE: bounswe
      MYSQL_USER: dev
      MYSQL_PASSWORD: dontusethispasswordtoo
    
  app:
    depends_on:
      - db
    build: .
    ports:
      - "8080:3000"
    environment:
      MYSQL_USERNAME: dev
      MYSQL_PASSWORD: dontusethispasswordtoo
      MYSQL_INSTANCE_NAME: bounswe
      MYSQL_PORT_3306_TCP_ADDR: db
      MYSQL_PORT_3306_TCP_PORT: 3306
      FLASK_ENV: development
    volumes:
      - .:/app
volumes:
  db_data: {}