name: Deploy to Test

on:
  push:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.5'
      -
        run: |
          cd python-mysql-sample
          pip install -r requirements.txt
          python test.py
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: python-mysql-sample
          push: true
          tags: vedit/python-mysql-sample:${{ github.sha }}
      - 
        name: Deploy to Test
        uses: fifsky/ssh-action@master
        with:
          command: |
            docker kill app || true
            docker rm app || true
            docker run -d --name app -E MYSQL_USERNAME=dev -E MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }} -E MYSQL_INSTANCE_NAME=bounswe -E MYSQL_PORT_3306_TCP_ADDR="172.31.6.113" -E MYSQL_PORT_3306_TCP_PORT="3306" -p 8080:3000 vedit/python-mysql-sample:${{ github.sha }}
          host: ${{ secrets.HOST }}
          user: ubuntu
          key: ${{ secrets.PRIVATE_KEY}}